### ISSUE TITLE
Sugggestion: Change the title color

### ISSUE THREAD

**Issue by liooalejandro** [lionel1989/github-crash-course#1]
Better h1 oranger:

Le pondira este codigo

```css
h1 {
  color: #b07e28;
}
```
